/**
 * Behavior taxonomy seed.
 *
 * Run with: bun run supabase/seeds/behavior_taxonomy.ts
 *
 * Requires env: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 * Idempotent: upserts on behavior_key.
 */
import { createClient } from "@supabase/supabase-js";

type DataType =
  | "boolean"
  | "count"
  | "numeric"
  | "scale_1_10"
  | "time_of_day"
  | "duration_minutes"
  | "text";

type Category =
  | "drugs_medication"
  | "health_symptoms"
  | "hormonal_health"
  | "lifestyle"
  | "mental_wellbeing"
  | "nutrition"
  | "recovery"
  | "sleep_circadian"
  | "supplements"
  | "epilepsy_specific";

interface BehaviorRow {
  category: Category;
  behavior_key: string;
  behavior_label: string;
  prompt_example: string;
  data_type: DataType;
  unit?: string | null;
  aliases?: string[];
}

const rows: BehaviorRow[] = [
  // ---------- drugs_medication (AEDs + common adjuncts + recreational) ----------
  {
    category: "drugs_medication",
    behavior_key: "keppra_dose",
    behavior_label: "Levetiracetam (Keppra) dose",
    prompt_example: "took 500mg of Keppra this morning",
    data_type: "numeric",
    unit: "mg",
    aliases: ["keppra", "levetiracetam", "seizure med", "kepra"],
  },
  {
    category: "drugs_medication",
    behavior_key: "lamictal_dose",
    behavior_label: "Lamotrigine (Lamictal) dose",
    prompt_example: "100mg lamictal with breakfast",
    data_type: "numeric",
    unit: "mg",
    aliases: ["lamictal", "lamotrigine"],
  },
  {
    category: "drugs_medication",
    behavior_key: "depakote_dose",
    behavior_label: "Valproate (Depakote) dose",
    prompt_example: "500mg depakote at night",
    data_type: "numeric",
    unit: "mg",
    aliases: ["depakote", "valproate", "valproic acid", "depakene"],
  },
  {
    category: "drugs_medication",
    behavior_key: "tegretol_dose",
    behavior_label: "Carbamazepine (Tegretol) dose",
    prompt_example: "took 200mg tegretol",
    data_type: "numeric",
    unit: "mg",
    aliases: ["tegretol", "carbamazepine", "carbatrol"],
  },
  {
    category: "drugs_medication",
    behavior_key: "trileptal_dose",
    behavior_label: "Oxcarbazepine (Trileptal) dose",
    prompt_example: "300mg trileptal twice today",
    data_type: "numeric",
    unit: "mg",
    aliases: ["trileptal", "oxcarbazepine"],
  },
  {
    category: "drugs_medication",
    behavior_key: "onfi_dose",
    behavior_label: "Clobazam (Onfi) dose",
    prompt_example: "10mg onfi at bedtime",
    data_type: "numeric",
    unit: "mg",
    aliases: ["onfi", "clobazam", "frisium"],
  },
  {
    category: "drugs_medication",
    behavior_key: "vimpat_dose",
    behavior_label: "Lacosamide (Vimpat) dose",
    prompt_example: "took 100mg vimpat",
    data_type: "numeric",
    unit: "mg",
    aliases: ["vimpat", "lacosamide"],
  },
  {
    category: "drugs_medication",
    behavior_key: "topamax_dose",
    behavior_label: "Topiramate (Topamax) dose",
    prompt_example: "50mg topamax this morning",
    data_type: "numeric",
    unit: "mg",
    aliases: ["topamax", "topiramate"],
  },
  {
    category: "drugs_medication",
    behavior_key: "zonegran_dose",
    behavior_label: "Zonisamide (Zonegran) dose",
    prompt_example: "took 100mg zonegran",
    data_type: "numeric",
    unit: "mg",
    aliases: ["zonegran", "zonisamide"],
  },
  {
    category: "drugs_medication",
    behavior_key: "briviact_dose",
    behavior_label: "Brivaracetam (Briviact) dose",
    prompt_example: "50mg briviact morning dose",
    data_type: "numeric",
    unit: "mg",
    aliases: ["briviact", "brivaracetam"],
  },
  {
    category: "drugs_medication",
    behavior_key: "neurontin_dose",
    behavior_label: "Gabapentin (Neurontin) dose",
    prompt_example: "took 300mg gabapentin",
    data_type: "numeric",
    unit: "mg",
    aliases: ["neurontin", "gabapentin"],
  },
  {
    category: "drugs_medication",
    behavior_key: "lyrica_dose",
    behavior_label: "Pregabalin (Lyrica) dose",
    prompt_example: "75mg lyrica before bed",
    data_type: "numeric",
    unit: "mg",
    aliases: ["lyrica", "pregabalin"],
  },
  {
    category: "drugs_medication",
    behavior_key: "dilantin_dose",
    behavior_label: "Phenytoin (Dilantin) dose",
    prompt_example: "took dilantin 100mg",
    data_type: "numeric",
    unit: "mg",
    aliases: ["dilantin", "phenytoin"],
  },
  {
    category: "drugs_medication",
    behavior_key: "phenobarbital_dose",
    behavior_label: "Phenobarbital dose",
    prompt_example: "60mg phenobarb tonight",
    data_type: "numeric",
    unit: "mg",
    aliases: ["phenobarbital", "phenobarb", "luminal"],
  },
  {
    category: "drugs_medication",
    behavior_key: "klonopin_dose",
    behavior_label: "Clonazepam (Klonopin) dose",
    prompt_example: "took 0.5mg klonopin",
    data_type: "numeric",
    unit: "mg",
    aliases: ["klonopin", "clonazepam", "rivotril"],
  },
  {
    category: "drugs_medication",
    behavior_key: "ativan_dose",
    behavior_label: "Lorazepam (Ativan) dose",
    prompt_example: "1mg ativan for anxiety",
    data_type: "numeric",
    unit: "mg",
    aliases: ["ativan", "lorazepam"],
  },
  {
    category: "drugs_medication",
    behavior_key: "xcopri_dose",
    behavior_label: "Cenobamate (Xcopri) dose",
    prompt_example: "took 100mg xcopri",
    data_type: "numeric",
    unit: "mg",
    aliases: ["xcopri", "cenobamate"],
  },
  {
    category: "drugs_medication",
    behavior_key: "ssri_taken",
    behavior_label: "SSRI taken",
    prompt_example: "took my sertraline",
    data_type: "boolean",
    aliases: ["zoloft", "lexapro", "prozac", "ssri", "antidepressant"],
  },
  {
    category: "drugs_medication",
    behavior_key: "adhd_stimulant",
    behavior_label: "ADHD stimulant taken",
    prompt_example: "took adderall this morning",
    data_type: "boolean",
    aliases: ["adderall", "vyvanse", "ritalin", "concerta", "stimulant"],
  },
  {
    category: "drugs_medication",
    behavior_key: "thc_use",
    behavior_label: "THC / cannabis use",
    prompt_example: "smoked weed last night",
    data_type: "boolean",
    aliases: ["weed", "cannabis", "marijuana", "thc", "edible"],
  },
  {
    category: "drugs_medication",
    behavior_key: "cbd_dose",
    behavior_label: "CBD dose",
    prompt_example: "took 25mg cbd oil",
    data_type: "numeric",
    unit: "mg",
    aliases: ["cbd", "cannabidiol", "epidiolex"],
  },
  {
    category: "drugs_medication",
    behavior_key: "nsaid_use",
    behavior_label: "NSAID use",
    prompt_example: "took ibuprofen for headache",
    data_type: "boolean",
    aliases: ["ibuprofen", "advil", "naproxen", "aleve", "nsaid"],
  },
  {
    category: "drugs_medication",
    behavior_key: "acetaminophen_dose",
    behavior_label: "Acetaminophen dose",
    prompt_example: "500mg tylenol",
    data_type: "numeric",
    unit: "mg",
    aliases: ["tylenol", "paracetamol", "acetaminophen"],
  },
  {
    category: "drugs_medication",
    behavior_key: "antibiotic_course",
    behavior_label: "On antibiotics",
    prompt_example: "started amoxicillin today",
    data_type: "boolean",
    aliases: ["antibiotic", "amoxicillin", "azithromycin"],
  },
  {
    category: "drugs_medication",
    behavior_key: "birth_control_taken",
    behavior_label: "Birth control taken",
    prompt_example: "took my pill",
    data_type: "boolean",
    aliases: ["pill", "birth control", "contraceptive", "ocp"],
  },

  // ---------- health_symptoms ----------
  {
    category: "health_symptoms",
    behavior_key: "headache_severity",
    behavior_label: "Headache severity",
    prompt_example: "bad headache, maybe 7 out of 10",
    data_type: "scale_1_10",
    aliases: ["headache", "migraine", "head pain"],
  },
  {
    category: "health_symptoms",
    behavior_key: "migraine_episode",
    behavior_label: "Migraine episode",
    prompt_example: "had a migraine this afternoon",
    data_type: "boolean",
    aliases: ["migraine"],
  },
  {
    category: "health_symptoms",
    behavior_key: "nausea",
    behavior_label: "Nausea",
    prompt_example: "felt nauseous after lunch",
    data_type: "boolean",
    aliases: ["nauseous", "queasy", "sick to stomach"],
  },
  {
    category: "health_symptoms",
    behavior_key: "vomiting",
    behavior_label: "Vomiting",
    prompt_example: "threw up this morning",
    data_type: "boolean",
    aliases: ["vomit", "threw up", "puked"],
  },
  {
    category: "health_symptoms",
    behavior_key: "dizziness",
    behavior_label: "Dizziness",
    prompt_example: "felt dizzy when I stood up",
    data_type: "boolean",
    aliases: ["dizzy", "lightheaded", "vertigo"],
  },
  {
    category: "health_symptoms",
    behavior_key: "fatigue_level",
    behavior_label: "Fatigue level",
    prompt_example: "exhausted today, 8/10 tired",
    data_type: "scale_1_10",
    aliases: ["tired", "exhausted", "fatigue"],
  },
  {
    category: "health_symptoms",
    behavior_key: "brain_fog",
    behavior_label: "Brain fog",
    prompt_example: "super foggy this morning",
    data_type: "scale_1_10",
    aliases: ["foggy", "brain fog", "cloudy head"],
  },
  {
    category: "health_symptoms",
    behavior_key: "fever",
    behavior_label: "Fever",
    prompt_example: "running a fever 101",
    data_type: "numeric",
    unit: "F",
    aliases: ["fever", "temperature"],
  },
  {
    category: "health_symptoms",
    behavior_key: "cold_symptoms",
    behavior_label: "Cold symptoms",
    prompt_example: "coming down with a cold",
    data_type: "boolean",
    aliases: ["cold", "runny nose", "congested"],
  },
  {
    category: "health_symptoms",
    behavior_key: "flu_symptoms",
    behavior_label: "Flu symptoms",
    prompt_example: "think I have the flu",
    data_type: "boolean",
    aliases: ["flu", "influenza"],
  },
  {
    category: "health_symptoms",
    behavior_key: "sore_throat",
    behavior_label: "Sore throat",
    prompt_example: "throat is sore",
    data_type: "boolean",
    aliases: ["sore throat"],
  },
  {
    category: "health_symptoms",
    behavior_key: "cough",
    behavior_label: "Cough",
    prompt_example: "been coughing all day",
    data_type: "boolean",
    aliases: ["cough", "coughing"],
  },
  {
    category: "health_symptoms",
    behavior_key: "diarrhea",
    behavior_label: "Diarrhea",
    prompt_example: "stomach was off, diarrhea",
    data_type: "boolean",
    aliases: ["diarrhea", "loose stool"],
  },
  {
    category: "health_symptoms",
    behavior_key: "constipation",
    behavior_label: "Constipation",
    prompt_example: "constipated",
    data_type: "boolean",
    aliases: ["constipated", "constipation"],
  },
  {
    category: "health_symptoms",
    behavior_key: "bloating",
    behavior_label: "Bloating",
    prompt_example: "really bloated after dinner",
    data_type: "boolean",
    aliases: ["bloated", "bloating"],
  },
  {
    category: "health_symptoms",
    behavior_key: "muscle_soreness",
    behavior_label: "Muscle soreness",
    prompt_example: "legs are sore from yesterday",
    data_type: "scale_1_10",
    aliases: ["sore", "doms", "muscle pain"],
  },
  {
    category: "health_symptoms",
    behavior_key: "joint_pain",
    behavior_label: "Joint pain",
    prompt_example: "knees aching today",
    data_type: "scale_1_10",
    aliases: ["joint pain", "arthritis"],
  },
  {
    category: "health_symptoms",
    behavior_key: "back_pain",
    behavior_label: "Back pain",
    prompt_example: "lower back pain 6/10",
    data_type: "scale_1_10",
    aliases: ["back pain", "lower back"],
  },
  {
    category: "health_symptoms",
    behavior_key: "chest_tightness",
    behavior_label: "Chest tightness",
    prompt_example: "tight chest this morning",
    data_type: "boolean",
    aliases: ["chest tight", "chest pressure"],
  },
  {
    category: "health_symptoms",
    behavior_key: "heart_palpitations",
    behavior_label: "Heart palpitations",
    prompt_example: "heart was racing earlier",
    data_type: "boolean",
    aliases: ["palpitations", "racing heart", "heart fluttering"],
  },
  {
    category: "health_symptoms",
    behavior_key: "shortness_of_breath",
    behavior_label: "Shortness of breath",
    prompt_example: "had trouble catching my breath",
    data_type: "boolean",
    aliases: ["short of breath", "winded", "dyspnea"],
  },
  {
    category: "health_symptoms",
    behavior_key: "tinnitus",
    behavior_label: "Tinnitus / ringing",
    prompt_example: "ears ringing today",
    data_type: "boolean",
    aliases: ["ringing ears", "tinnitus"],
  },
  {
    category: "health_symptoms",
    behavior_key: "skin_rash",
    behavior_label: "Skin rash",
    prompt_example: "got a rash on my arm",
    data_type: "boolean",
    aliases: ["rash", "hives", "skin irritation"],
  },
  {
    category: "health_symptoms",
    behavior_key: "allergies_active",
    behavior_label: "Active allergies",
    prompt_example: "allergies are bad today",
    data_type: "boolean",
    aliases: ["allergies", "pollen", "hay fever"],
  },
  {
    category: "health_symptoms",
    behavior_key: "menstrual_cramps",
    behavior_label: "Menstrual cramps",
    prompt_example: "cramps 7/10 today",
    data_type: "scale_1_10",
    aliases: ["cramps", "period pain"],
  },

  // ---------- hormonal_health ----------
  {
    category: "hormonal_health",
    behavior_key: "menstrual_cycle_day",
    behavior_label: "Menstrual cycle day",
    prompt_example: "day 3 of my period",
    data_type: "count",
    aliases: ["cycle day", "period day"],
  },
  {
    category: "hormonal_health",
    behavior_key: "menstrual_flow",
    behavior_label: "Menstrual flow",
    prompt_example: "heavy flow today",
    data_type: "text",
    aliases: ["flow", "period heavy", "period light"],
  },
  {
    category: "hormonal_health",
    behavior_key: "period_started",
    behavior_label: "Period started",
    prompt_example: "period started today",
    data_type: "boolean",
    aliases: ["period", "menstruation", "started bleeding"],
  },
  {
    category: "hormonal_health",
    behavior_key: "ovulation_window",
    behavior_label: "Ovulation window",
    prompt_example: "ovulating today",
    data_type: "boolean",
    aliases: ["ovulation", "ovulating"],
  },
  {
    category: "hormonal_health",
    behavior_key: "pms_symptoms",
    behavior_label: "PMS symptoms",
    prompt_example: "pms is rough",
    data_type: "scale_1_10",
    aliases: ["pms", "premenstrual"],
  },
  {
    category: "hormonal_health",
    behavior_key: "pmdd_symptoms",
    behavior_label: "PMDD symptoms",
    prompt_example: "pmdd hitting hard",
    data_type: "scale_1_10",
    aliases: ["pmdd"],
  },
  {
    category: "hormonal_health",
    behavior_key: "hormonal_contraceptive_taken",
    behavior_label: "Hormonal contraceptive taken",
    prompt_example: "took my pill",
    data_type: "boolean",
    aliases: ["birth control", "the pill"],
  },
  {
    category: "hormonal_health",
    behavior_key: "hrt_taken",
    behavior_label: "Hormone replacement therapy taken",
    prompt_example: "took my estrogen patch",
    data_type: "boolean",
    aliases: ["hrt", "estrogen", "progesterone", "testosterone"],
  },
  {
    category: "hormonal_health",
    behavior_key: "menopause_symptoms",
    behavior_label: "Menopause symptoms",
    prompt_example: "hot flashes all day",
    data_type: "boolean",
    aliases: ["menopause", "perimenopause", "hot flash"],
  },
  {
    category: "hormonal_health",
    behavior_key: "pregnancy_status",
    behavior_label: "Pregnancy status",
    prompt_example: "12 weeks pregnant now",
    data_type: "text",
    aliases: ["pregnant", "pregnancy"],
  },
  {
    category: "hormonal_health",
    behavior_key: "breastfeeding",
    behavior_label: "Breastfeeding",
    prompt_example: "still breastfeeding",
    data_type: "boolean",
    aliases: ["breastfeeding", "nursing", "lactating"],
  },
  {
    category: "hormonal_health",
    behavior_key: "thyroid_med_taken",
    behavior_label: "Thyroid medication taken",
    prompt_example: "took my synthroid",
    data_type: "boolean",
    aliases: ["synthroid", "levothyroxine", "thyroid med"],
  },
  {
    category: "hormonal_health",
    behavior_key: "libido_level",
    behavior_label: "Libido level",
    prompt_example: "libido feels low this week",
    data_type: "scale_1_10",
    aliases: ["libido", "sex drive"],
  },
  {
    category: "hormonal_health",
    behavior_key: "breast_tenderness",
    behavior_label: "Breast tenderness",
    prompt_example: "breasts sore today",
    data_type: "boolean",
    aliases: ["breast pain", "tender breasts"],
  },
  {
    category: "hormonal_health",
    behavior_key: "acne_flare",
    behavior_label: "Hormonal acne flare",
    prompt_example: "chin breakout again",
    data_type: "boolean",
    aliases: ["acne", "breakout", "pimples"],
  },
  {
    category: "hormonal_health",
    behavior_key: "ttc",
    behavior_label: "Trying to conceive",
    prompt_example: "we're ttc this cycle",
    data_type: "boolean",
    aliases: ["ttc", "trying to conceive"],
  },

  // ---------- lifestyle ----------
  {
    category: "lifestyle",
    behavior_key: "alcohol_drinks",
    behavior_label: "Alcoholic drinks",
    prompt_example: "had 2 beers with dinner",
    data_type: "count",
    unit: "drinks",
    aliases: ["beer", "wine", "drinks", "alcohol", "cocktail"],
  },
  {
    category: "lifestyle",
    behavior_key: "nicotine_use",
    behavior_label: "Nicotine use",
    prompt_example: "smoked a cigarette",
    data_type: "boolean",
    aliases: ["cigarette", "vape", "nicotine", "smoke"],
  },
  {
    category: "lifestyle",
    behavior_key: "exercise_duration",
    behavior_label: "Exercise duration",
    prompt_example: "ran for 45 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["workout", "exercise", "ran", "lifted", "gym"],
  },
  {
    category: "lifestyle",
    behavior_key: "exercise_intensity",
    behavior_label: "Exercise intensity",
    prompt_example: "hard workout, intensity 8",
    data_type: "scale_1_10",
    aliases: ["intensity", "hard workout"],
  },
  {
    category: "lifestyle",
    behavior_key: "steps_count",
    behavior_label: "Steps taken",
    prompt_example: "got 10k steps",
    data_type: "count",
    unit: "steps",
    aliases: ["steps", "walked"],
  },
  {
    category: "lifestyle",
    behavior_key: "outdoor_time",
    behavior_label: "Time outdoors",
    prompt_example: "30 min walk outside",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["outside", "outdoors", "walk"],
  },
  {
    category: "lifestyle",
    behavior_key: "sun_exposure",
    behavior_label: "Sun exposure",
    prompt_example: "got a lot of sun today",
    data_type: "scale_1_10",
    aliases: ["sun", "sunlight", "sunshine"],
  },
  {
    category: "lifestyle",
    behavior_key: "screen_time_hours",
    behavior_label: "Screen time",
    prompt_example: "way too much screen time, like 8 hours",
    data_type: "numeric",
    unit: "hours",
    aliases: ["screen time", "phone time"],
  },
  {
    category: "lifestyle",
    behavior_key: "work_hours",
    behavior_label: "Work hours",
    prompt_example: "worked 9 hours today",
    data_type: "numeric",
    unit: "hours",
    aliases: ["work", "worked", "office hours"],
  },
  {
    category: "lifestyle",
    behavior_key: "commute_time",
    behavior_label: "Commute time",
    prompt_example: "1 hour commute each way",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["commute"],
  },
  {
    category: "lifestyle",
    behavior_key: "travel_day",
    behavior_label: "Travel day",
    prompt_example: "flew to chicago",
    data_type: "boolean",
    aliases: ["flew", "flight", "traveled", "road trip"],
  },
  {
    category: "lifestyle",
    behavior_key: "timezone_change",
    behavior_label: "Timezone change",
    prompt_example: "jet lagged from 3 hour shift",
    data_type: "numeric",
    unit: "hours",
    aliases: ["jet lag", "timezone"],
  },
  {
    category: "lifestyle",
    behavior_key: "social_interaction",
    behavior_label: "Social interaction quality",
    prompt_example: "great dinner with friends",
    data_type: "scale_1_10",
    aliases: ["social", "friends", "hangout"],
  },
  {
    category: "lifestyle",
    behavior_key: "solo_time",
    behavior_label: "Time alone",
    prompt_example: "spent the day alone",
    data_type: "boolean",
    aliases: ["alone", "solo", "by myself"],
  },
  {
    category: "lifestyle",
    behavior_key: "sauna_session",
    behavior_label: "Sauna session",
    prompt_example: "20 min in the sauna",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["sauna"],
  },
  {
    category: "lifestyle",
    behavior_key: "cold_plunge",
    behavior_label: "Cold plunge / cold shower",
    prompt_example: "cold plunge for 3 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["cold plunge", "ice bath", "cold shower"],
  },
  {
    category: "lifestyle",
    behavior_key: "shower_taken",
    behavior_label: "Shower taken",
    prompt_example: "showered before bed",
    data_type: "boolean",
    aliases: ["shower", "bath"],
  },
  {
    category: "lifestyle",
    behavior_key: "sex_activity",
    behavior_label: "Sexual activity",
    prompt_example: "had sex last night",
    data_type: "boolean",
    aliases: ["sex", "intimacy"],
  },
  {
    category: "lifestyle",
    behavior_key: "driving_time",
    behavior_label: "Driving time",
    prompt_example: "drove for 2 hours",
    data_type: "numeric",
    unit: "hours",
    aliases: ["drove", "driving"],
  },
  {
    category: "lifestyle",
    behavior_key: "loud_environment",
    behavior_label: "Loud environment exposure",
    prompt_example: "concert was super loud",
    data_type: "boolean",
    aliases: ["loud", "concert", "club"],
  },

  // ---------- mental_wellbeing ----------
  {
    category: "mental_wellbeing",
    behavior_key: "mood_rating",
    behavior_label: "Overall mood",
    prompt_example: "feeling pretty good, 7/10",
    data_type: "scale_1_10",
    aliases: ["mood", "feeling"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "stress_level",
    behavior_label: "Stress level",
    prompt_example: "stressed out, 8/10",
    data_type: "scale_1_10",
    aliases: ["stress", "stressed"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "anxiety_level",
    behavior_label: "Anxiety level",
    prompt_example: "anxious all day",
    data_type: "scale_1_10",
    aliases: ["anxious", "anxiety"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "depression_level",
    behavior_label: "Depression / low mood",
    prompt_example: "really low today",
    data_type: "scale_1_10",
    aliases: ["depressed", "low", "sad"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "irritability",
    behavior_label: "Irritability",
    prompt_example: "super irritable",
    data_type: "scale_1_10",
    aliases: ["irritable", "snappy", "short fuse"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "panic_attack",
    behavior_label: "Panic attack",
    prompt_example: "had a panic attack at work",
    data_type: "boolean",
    aliases: ["panic", "panic attack"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "meditation_session",
    behavior_label: "Meditation",
    prompt_example: "meditated for 15 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["meditate", "meditation", "mindfulness"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "breathwork",
    behavior_label: "Breathwork",
    prompt_example: "10 min box breathing",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["breathwork", "breathing exercise"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "journaling",
    behavior_label: "Journaling",
    prompt_example: "journaled this morning",
    data_type: "boolean",
    aliases: ["journal", "wrote"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "therapy_session",
    behavior_label: "Therapy session",
    prompt_example: "had therapy today",
    data_type: "boolean",
    aliases: ["therapy", "therapist", "counseling"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "gratitude_practice",
    behavior_label: "Gratitude practice",
    prompt_example: "wrote 3 gratitudes",
    data_type: "boolean",
    aliases: ["gratitude", "thankful"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "focus_quality",
    behavior_label: "Focus quality",
    prompt_example: "couldn't focus, like 3/10",
    data_type: "scale_1_10",
    aliases: ["focus", "concentration"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "motivation_level",
    behavior_label: "Motivation level",
    prompt_example: "zero motivation today",
    data_type: "scale_1_10",
    aliases: ["motivation", "drive"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "energy_level",
    behavior_label: "Energy level",
    prompt_example: "energy is 8/10",
    data_type: "scale_1_10",
    aliases: ["energy"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "emotional_event",
    behavior_label: "Emotional event",
    prompt_example: "had an emotional argument with partner",
    data_type: "text",
    aliases: ["argument", "fight", "cried", "emotional"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "overwhelm_level",
    behavior_label: "Overwhelm",
    prompt_example: "totally overwhelmed",
    data_type: "scale_1_10",
    aliases: ["overwhelmed", "overwhelm"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "loneliness",
    behavior_label: "Loneliness",
    prompt_example: "feeling lonely",
    data_type: "scale_1_10",
    aliases: ["lonely", "isolated"],
  },
  {
    category: "mental_wellbeing",
    behavior_key: "self_compassion",
    behavior_label: "Self-compassion practice",
    prompt_example: "tried to be kind to myself",
    data_type: "boolean",
    aliases: ["self compassion"],
  },

  // ---------- nutrition ----------
  {
    category: "nutrition",
    behavior_key: "caffeine_intake",
    behavior_label: "Caffeine intake",
    prompt_example: "had coffee around 10am",
    data_type: "numeric",
    unit: "mg",
    aliases: ["coffee", "caffeine", "espresso", "cold brew", "tea"],
  },
  {
    category: "nutrition",
    behavior_key: "energy_drink",
    behavior_label: "Energy drink",
    prompt_example: "had a red bull",
    data_type: "count",
    unit: "servings",
    aliases: ["red bull", "monster", "energy drink", "celsius"],
  },
  {
    category: "nutrition",
    behavior_key: "water_intake",
    behavior_label: "Water intake",
    prompt_example: "drank about 2 liters",
    data_type: "numeric",
    unit: "liters",
    aliases: ["water", "hydration", "fluids"],
  },
  {
    category: "nutrition",
    behavior_key: "hydration_quality",
    behavior_label: "Hydration quality",
    prompt_example: "felt dehydrated",
    data_type: "scale_1_10",
    aliases: ["dehydrated", "hydration"],
  },
  {
    category: "nutrition",
    behavior_key: "electrolytes",
    behavior_label: "Electrolytes consumed",
    prompt_example: "had an lmnt packet",
    data_type: "boolean",
    aliases: ["lmnt", "electrolytes", "liquid iv"],
  },
  {
    category: "nutrition",
    behavior_key: "breakfast_eaten",
    behavior_label: "Breakfast eaten",
    prompt_example: "had eggs and toast",
    data_type: "boolean",
    aliases: ["breakfast"],
  },
  {
    category: "nutrition",
    behavior_key: "lunch_eaten",
    behavior_label: "Lunch eaten",
    prompt_example: "salad for lunch",
    data_type: "boolean",
    aliases: ["lunch"],
  },
  {
    category: "nutrition",
    behavior_key: "dinner_eaten",
    behavior_label: "Dinner eaten",
    prompt_example: "pasta for dinner",
    data_type: "boolean",
    aliases: ["dinner", "supper"],
  },
  {
    category: "nutrition",
    behavior_key: "last_meal_time",
    behavior_label: "Time of last meal",
    prompt_example: "last meal was 8pm",
    data_type: "time_of_day",
    aliases: ["last meal", "stopped eating"],
  },
  {
    category: "nutrition",
    behavior_key: "fasting_window",
    behavior_label: "Fasting window length",
    prompt_example: "fasted 16 hours",
    data_type: "numeric",
    unit: "hours",
    aliases: ["fasting", "if", "intermittent fasting"],
  },
  {
    category: "nutrition",
    behavior_key: "sugar_intake",
    behavior_label: "Sugar intake",
    prompt_example: "ate way too much sugar",
    data_type: "scale_1_10",
    aliases: ["sugar", "sweets", "dessert"],
  },
  {
    category: "nutrition",
    behavior_key: "processed_food",
    behavior_label: "Processed food intake",
    prompt_example: "lots of junk food today",
    data_type: "scale_1_10",
    aliases: ["junk food", "processed", "fast food"],
  },
  {
    category: "nutrition",
    behavior_key: "protein_grams",
    behavior_label: "Protein intake",
    prompt_example: "hit 120g protein",
    data_type: "numeric",
    unit: "g",
    aliases: ["protein"],
  },
  {
    category: "nutrition",
    behavior_key: "carb_intake",
    behavior_label: "Carb intake level",
    prompt_example: "high carb day",
    data_type: "scale_1_10",
    aliases: ["carbs", "carbohydrates"],
  },
  {
    category: "nutrition",
    behavior_key: "fiber_intake",
    behavior_label: "Fiber intake",
    prompt_example: "lots of veggies today",
    data_type: "scale_1_10",
    aliases: ["fiber", "vegetables", "veggies"],
  },
  {
    category: "nutrition",
    behavior_key: "ketogenic_diet",
    behavior_label: "Following ketogenic diet",
    prompt_example: "stayed in ketosis",
    data_type: "boolean",
    aliases: ["keto", "ketogenic", "ketosis"],
  },
  {
    category: "nutrition",
    behavior_key: "modified_atkins_diet",
    behavior_label: "Modified Atkins (MAD)",
    prompt_example: "stuck to mad today",
    data_type: "boolean",
    aliases: ["modified atkins", "mad diet"],
  },
  {
    category: "nutrition",
    behavior_key: "low_glycemic_diet",
    behavior_label: "Low glycemic index diet",
    prompt_example: "kept it low gi",
    data_type: "boolean",
    aliases: ["low gi", "low glycemic"],
  },
  {
    category: "nutrition",
    behavior_key: "gluten_free",
    behavior_label: "Gluten free",
    prompt_example: "stayed gluten free",
    data_type: "boolean",
    aliases: ["gluten free", "no gluten"],
  },
  {
    category: "nutrition",
    behavior_key: "dairy_free",
    behavior_label: "Dairy free",
    prompt_example: "avoided dairy",
    data_type: "boolean",
    aliases: ["dairy free", "no dairy"],
  },
  {
    category: "nutrition",
    behavior_key: "vegetarian",
    behavior_label: "Vegetarian day",
    prompt_example: "no meat today",
    data_type: "boolean",
    aliases: ["vegetarian", "no meat"],
  },
  {
    category: "nutrition",
    behavior_key: "alcohol_with_food",
    behavior_label: "Alcohol with food",
    prompt_example: "wine with dinner",
    data_type: "boolean",
    aliases: ["wine with dinner"],
  },
  {
    category: "nutrition",
    behavior_key: "late_night_eating",
    behavior_label: "Late night eating",
    prompt_example: "snacked at midnight",
    data_type: "boolean",
    aliases: ["late snack", "midnight snack"],
  },
  {
    category: "nutrition",
    behavior_key: "meal_satisfaction",
    behavior_label: "Meal satisfaction",
    prompt_example: "really satisfying meal",
    data_type: "scale_1_10",
    aliases: ["satisfied", "full"],
  },

  // ---------- recovery ----------
  {
    category: "recovery",
    behavior_key: "stretching_session",
    behavior_label: "Stretching",
    prompt_example: "stretched for 20 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["stretch", "stretching"],
  },
  {
    category: "recovery",
    behavior_key: "foam_rolling",
    behavior_label: "Foam rolling",
    prompt_example: "foam rolled my legs",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["foam roll", "myofascial"],
  },
  {
    category: "recovery",
    behavior_key: "massage",
    behavior_label: "Massage",
    prompt_example: "got a massage",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["massage"],
  },
  {
    category: "recovery",
    behavior_key: "yoga_session",
    behavior_label: "Yoga",
    prompt_example: "30 min yoga flow",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["yoga"],
  },
  {
    category: "recovery",
    behavior_key: "rest_day",
    behavior_label: "Rest day",
    prompt_example: "took a rest day",
    data_type: "boolean",
    aliases: ["rest day", "off day"],
  },
  {
    category: "recovery",
    behavior_key: "active_recovery",
    behavior_label: "Active recovery",
    prompt_example: "easy walk for recovery",
    data_type: "boolean",
    aliases: ["active recovery", "easy day"],
  },
  {
    category: "recovery",
    behavior_key: "compression_garments",
    behavior_label: "Compression garments",
    prompt_example: "wore compression socks",
    data_type: "boolean",
    aliases: ["compression", "compression socks"],
  },
  {
    category: "recovery",
    behavior_key: "nap_duration",
    behavior_label: "Nap duration",
    prompt_example: "took a 30 min nap",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["nap", "napped"],
  },
  {
    category: "recovery",
    behavior_key: "ice_therapy",
    behavior_label: "Ice / cryotherapy",
    prompt_example: "iced my knee",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["ice", "cryo", "icepack"],
  },
  {
    category: "recovery",
    behavior_key: "heat_therapy",
    behavior_label: "Heat therapy",
    prompt_example: "heating pad on back",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["heat", "heating pad"],
  },
  {
    category: "recovery",
    behavior_key: "physical_therapy",
    behavior_label: "Physical therapy session",
    prompt_example: "had pt this morning",
    data_type: "boolean",
    aliases: ["pt", "physical therapy", "physio"],
  },
  {
    category: "recovery",
    behavior_key: "soreness_recovery",
    behavior_label: "Perceived recovery",
    prompt_example: "feeling 7/10 recovered",
    data_type: "scale_1_10",
    aliases: ["recovered", "recovery feel"],
  },
  {
    category: "recovery",
    behavior_key: "redlight_therapy",
    behavior_label: "Red light therapy",
    prompt_example: "10 min red light",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["red light", "rlt", "photobiomodulation"],
  },
  {
    category: "recovery",
    behavior_key: "hot_tub",
    behavior_label: "Hot tub / hot bath",
    prompt_example: "soaked in the hot tub",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["hot tub", "jacuzzi", "hot bath"],
  },
  {
    category: "recovery",
    behavior_key: "walk_after_meal",
    behavior_label: "Walk after meal",
    prompt_example: "walked after dinner",
    data_type: "boolean",
    aliases: ["post meal walk", "walked after"],
  },

  // ---------- sleep_circadian ----------
  {
    category: "sleep_circadian",
    behavior_key: "bedtime",
    behavior_label: "Bedtime",
    prompt_example: "in bed by 11pm",
    data_type: "time_of_day",
    aliases: ["bedtime", "went to bed", "in bed"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "wake_time",
    behavior_label: "Wake time",
    prompt_example: "woke up at 6:30",
    data_type: "time_of_day",
    aliases: ["woke up", "wake time", "alarm"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "sleep_duration_hours",
    behavior_label: "Sleep duration",
    prompt_example: "got about 7.5 hours of sleep",
    data_type: "numeric",
    unit: "hours",
    aliases: ["slept", "sleep", "hours of sleep"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "sleep_quality",
    behavior_label: "Sleep quality",
    prompt_example: "slept terribly, 3/10",
    data_type: "scale_1_10",
    aliases: ["sleep quality", "slept well", "slept bad"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "night_wakings",
    behavior_label: "Night wakings",
    prompt_example: "woke up 3 times",
    data_type: "count",
    aliases: ["woke up", "night waking"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "sleep_latency_minutes",
    behavior_label: "Time to fall asleep",
    prompt_example: "took an hour to fall asleep",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["fall asleep", "couldn't sleep"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "dreams_vivid",
    behavior_label: "Vivid dreams",
    prompt_example: "really vivid dreams last night",
    data_type: "boolean",
    aliases: ["dreams", "vivid dream", "nightmare"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "nightmares",
    behavior_label: "Nightmares",
    prompt_example: "nightmares woke me up",
    data_type: "boolean",
    aliases: ["nightmare", "bad dream"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "consistent_sleep_schedule",
    behavior_label: "Consistent sleep schedule",
    prompt_example: "same bedtime as usual",
    data_type: "boolean",
    aliases: ["consistent sleep", "regular schedule"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "blue_light_late",
    behavior_label: "Blue light before bed",
    prompt_example: "scrolled phone in bed",
    data_type: "boolean",
    aliases: ["phone in bed", "screen before bed"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "morning_light",
    behavior_label: "Morning light exposure",
    prompt_example: "got sunlight first thing",
    data_type: "boolean",
    aliases: ["morning sun", "morning light"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "bedroom_temperature_cool",
    behavior_label: "Cool bedroom",
    prompt_example: "kept bedroom cool",
    data_type: "boolean",
    aliases: ["cool bedroom", "ac on"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "snoring",
    behavior_label: "Snoring reported",
    prompt_example: "partner said I snored",
    data_type: "boolean",
    aliases: ["snored", "snoring"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "sleep_aid_used",
    behavior_label: "Sleep aid used",
    prompt_example: "took melatonin",
    data_type: "boolean",
    aliases: ["sleep aid", "ambien", "trazodone"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "rem_disruption",
    behavior_label: "REM disruption felt",
    prompt_example: "woke during a dream a lot",
    data_type: "boolean",
    aliases: ["rem", "rem sleep"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "morning_grogginess",
    behavior_label: "Morning grogginess",
    prompt_example: "groggy when I woke",
    data_type: "scale_1_10",
    aliases: ["groggy", "grogginess"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "shift_work",
    behavior_label: "Shift work / night shift",
    prompt_example: "worked overnight shift",
    data_type: "boolean",
    aliases: ["night shift", "overnight", "shift work"],
  },
  {
    category: "sleep_circadian",
    behavior_key: "caffeine_after_noon",
    behavior_label: "Caffeine after noon",
    prompt_example: "had coffee at 4pm",
    data_type: "boolean",
    aliases: ["late coffee", "afternoon coffee"],
  },

  // ---------- supplements ----------
  {
    category: "supplements",
    behavior_key: "melatonin_dose",
    behavior_label: "Melatonin dose",
    prompt_example: "took 3mg melatonin",
    data_type: "numeric",
    unit: "mg",
    aliases: ["melatonin"],
  },
  {
    category: "supplements",
    behavior_key: "magnesium_dose",
    behavior_label: "Magnesium dose",
    prompt_example: "400mg magnesium glycinate",
    data_type: "numeric",
    unit: "mg",
    aliases: ["magnesium", "mag glycinate", "mag citrate"],
  },
  {
    category: "supplements",
    behavior_key: "vitamin_d_dose",
    behavior_label: "Vitamin D dose",
    prompt_example: "took 5000 iu vitamin d",
    data_type: "numeric",
    unit: "IU",
    aliases: ["vitamin d", "d3"],
  },
  {
    category: "supplements",
    behavior_key: "vitamin_b_complex",
    behavior_label: "B complex taken",
    prompt_example: "took my b complex",
    data_type: "boolean",
    aliases: ["b complex", "b vitamins"],
  },
  {
    category: "supplements",
    behavior_key: "vitamin_b6_dose",
    behavior_label: "Vitamin B6 dose",
    prompt_example: "50mg b6",
    data_type: "numeric",
    unit: "mg",
    aliases: ["b6", "pyridoxine"],
  },
  {
    category: "supplements",
    behavior_key: "folate_dose",
    behavior_label: "Folate / B9 dose",
    prompt_example: "took 400mcg folate",
    data_type: "numeric",
    unit: "mcg",
    aliases: ["folate", "folic acid", "b9", "methylfolate"],
  },
  {
    category: "supplements",
    behavior_key: "omega3_dose",
    behavior_label: "Omega-3 fish oil",
    prompt_example: "1g fish oil",
    data_type: "numeric",
    unit: "mg",
    aliases: ["fish oil", "omega 3", "epa", "dha"],
  },
  {
    category: "supplements",
    behavior_key: "iron_dose",
    behavior_label: "Iron supplement",
    prompt_example: "took iron with breakfast",
    data_type: "numeric",
    unit: "mg",
    aliases: ["iron", "ferrous sulfate"],
  },
  {
    category: "supplements",
    behavior_key: "zinc_dose",
    behavior_label: "Zinc dose",
    prompt_example: "15mg zinc",
    data_type: "numeric",
    unit: "mg",
    aliases: ["zinc"],
  },
  {
    category: "supplements",
    behavior_key: "probiotic_taken",
    behavior_label: "Probiotic taken",
    prompt_example: "took my probiotic",
    data_type: "boolean",
    aliases: ["probiotic"],
  },
  {
    category: "supplements",
    behavior_key: "creatine_dose",
    behavior_label: "Creatine dose",
    prompt_example: "5g creatine",
    data_type: "numeric",
    unit: "g",
    aliases: ["creatine"],
  },
  {
    category: "supplements",
    behavior_key: "protein_powder",
    behavior_label: "Protein powder serving",
    prompt_example: "had a protein shake",
    data_type: "count",
    unit: "servings",
    aliases: ["protein shake", "whey", "protein powder"],
  },
  {
    category: "supplements",
    behavior_key: "ashwagandha_dose",
    behavior_label: "Ashwagandha dose",
    prompt_example: "600mg ashwagandha",
    data_type: "numeric",
    unit: "mg",
    aliases: ["ashwagandha"],
  },
  {
    category: "supplements",
    behavior_key: "l_theanine_dose",
    behavior_label: "L-Theanine dose",
    prompt_example: "took 200mg theanine",
    data_type: "numeric",
    unit: "mg",
    aliases: ["theanine", "l-theanine"],
  },
  {
    category: "supplements",
    behavior_key: "rhodiola_taken",
    behavior_label: "Rhodiola taken",
    prompt_example: "took rhodiola",
    data_type: "boolean",
    aliases: ["rhodiola"],
  },
  {
    category: "supplements",
    behavior_key: "taurine_dose",
    behavior_label: "Taurine dose",
    prompt_example: "took 1g taurine",
    data_type: "numeric",
    unit: "mg",
    aliases: ["taurine"],
  },
  {
    category: "supplements",
    behavior_key: "multivitamin_taken",
    behavior_label: "Multivitamin taken",
    prompt_example: "took my multi",
    data_type: "boolean",
    aliases: ["multi", "multivitamin"],
  },
  {
    category: "supplements",
    behavior_key: "coq10_dose",
    behavior_label: "CoQ10 dose",
    prompt_example: "100mg coq10",
    data_type: "numeric",
    unit: "mg",
    aliases: ["coq10", "ubiquinol"],
  },
  {
    category: "supplements",
    behavior_key: "nac_dose",
    behavior_label: "NAC dose",
    prompt_example: "took 600mg nac",
    data_type: "numeric",
    unit: "mg",
    aliases: ["nac", "n-acetyl cysteine"],
  },
  {
    category: "supplements",
    behavior_key: "glycine_dose",
    behavior_label: "Glycine dose",
    prompt_example: "3g glycine before bed",
    data_type: "numeric",
    unit: "g",
    aliases: ["glycine"],
  },
  {
    category: "supplements",
    behavior_key: "vitamin_c_dose",
    behavior_label: "Vitamin C dose",
    prompt_example: "1000mg vitamin c",
    data_type: "numeric",
    unit: "mg",
    aliases: ["vitamin c", "ascorbic acid"],
  },
  {
    category: "supplements",
    behavior_key: "calcium_dose",
    behavior_label: "Calcium dose",
    prompt_example: "took calcium",
    data_type: "numeric",
    unit: "mg",
    aliases: ["calcium"],
  },

  // ---------- epilepsy_specific (~25) ----------
  {
    category: "epilepsy_specific",
    behavior_key: "seizure_occurred",
    behavior_label: "Seizure occurred",
    prompt_example: "had a seizure around 3pm",
    data_type: "boolean",
    aliases: ["seizure", "fit", "convulsion", "ictal event"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "seizure_type_observed",
    behavior_label: "Seizure type observed",
    prompt_example: "tonic clonic seizure today",
    data_type: "text",
    aliases: ["tonic clonic", "absence", "focal", "myoclonic", "atonic", "grand mal", "petit mal"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "seizure_duration_minutes",
    behavior_label: "Seizure duration",
    prompt_example: "seizure lasted about 2 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["seizure length", "seizure lasted"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "seizure_cluster",
    behavior_label: "Seizure cluster (multiple)",
    prompt_example: "had 3 seizures in a row",
    data_type: "boolean",
    aliases: ["cluster", "multiple seizures"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "aura_experienced",
    behavior_label: "Aura experienced",
    prompt_example: "felt the aura before it happened",
    data_type: "boolean",
    aliases: ["aura", "warning", "prodrome"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "aura_type",
    behavior_label: "Aura type / description",
    prompt_example: "aura was deja vu and a weird smell",
    data_type: "text",
    aliases: ["aura felt", "deja vu", "epigastric rising"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "postictal_state",
    behavior_label: "Postictal state",
    prompt_example: "really out of it after, postictal for hours",
    data_type: "scale_1_10",
    aliases: ["postictal", "after seizure", "recovery from seizure"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "postictal_duration_minutes",
    behavior_label: "Postictal duration",
    prompt_example: "postictal lasted 45 minutes",
    data_type: "duration_minutes",
    unit: "minutes",
    aliases: ["postictal length"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "missed_aed_dose",
    behavior_label: "Missed AED dose",
    prompt_example: "forgot to take my morning keppra",
    data_type: "boolean",
    aliases: ["missed dose", "forgot med", "skipped dose"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "late_aed_dose",
    behavior_label: "Late AED dose",
    prompt_example: "took my med 3 hours late",
    data_type: "boolean",
    aliases: ["late dose", "late med"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "rescue_med_used",
    behavior_label: "Rescue medication used",
    prompt_example: "had to use diazepam rescue",
    data_type: "boolean",
    aliases: ["rescue med", "diazepam", "valium", "midazolam", "nayzilam", "valtoco", "diastat"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "status_epilepticus_risk",
    behavior_label: "Status epilepticus risk event",
    prompt_example: "seizure lasted over 5 minutes, status risk",
    data_type: "boolean",
    aliases: ["status epilepticus", "status", "prolonged seizure"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "photic_trigger_exposure",
    behavior_label: "Photic trigger exposure",
    prompt_example: "flashing lights at the club",
    data_type: "boolean",
    aliases: ["flashing lights", "strobe", "photic", "flicker"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "pattern_trigger_exposure",
    behavior_label: "Pattern / visual trigger",
    prompt_example: "stripe pattern bothered me",
    data_type: "boolean",
    aliases: ["pattern trigger", "stripes"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "sleep_deprivation_trigger",
    behavior_label: "Sleep deprivation (known trigger)",
    prompt_example: "barely slept last night",
    data_type: "boolean",
    aliases: ["no sleep", "sleep deprived", "all nighter"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "missed_meal_trigger",
    behavior_label: "Missed meal (trigger)",
    prompt_example: "skipped lunch",
    data_type: "boolean",
    aliases: ["skipped meal", "missed meal"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "illness_trigger",
    behavior_label: "Illness / infection trigger",
    prompt_example: "fever and feeling sick",
    data_type: "boolean",
    aliases: ["sick", "infection", "fever trigger"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "menstrual_trigger",
    behavior_label: "Catamenial / menstrual trigger",
    prompt_example: "period started, catamenial pattern",
    data_type: "boolean",
    aliases: ["catamenial", "period seizure"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "stress_trigger",
    behavior_label: "Acute stress trigger",
    prompt_example: "huge stress at work today",
    data_type: "boolean",
    aliases: ["stress trigger", "big stress"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "alcohol_trigger",
    behavior_label: "Alcohol trigger",
    prompt_example: "drank a lot last night",
    data_type: "boolean",
    aliases: ["drinking", "heavy drinking"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "vns_swipe_used",
    behavior_label: "VNS magnet swipe used",
    prompt_example: "swiped my vns magnet",
    data_type: "count",
    aliases: ["vns", "magnet swipe", "vagus nerve stimulator"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "ketogenic_compliance",
    behavior_label: "Ketogenic diet compliance",
    prompt_example: "stayed in ketosis all day",
    data_type: "scale_1_10",
    aliases: ["keto compliance", "in ketosis"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "injury_from_seizure",
    behavior_label: "Injury from seizure",
    prompt_example: "bit my tongue and bruised my arm",
    data_type: "boolean",
    aliases: ["bit tongue", "fell during seizure", "injury seizure"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "incontinence_during_seizure",
    behavior_label: "Incontinence during seizure",
    prompt_example: "lost bladder control",
    data_type: "boolean",
    aliases: ["incontinence", "wet myself", "lost bladder"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "memory_gap",
    behavior_label: "Memory gap / lost time",
    prompt_example: "lost about 10 minutes I can't account for",
    data_type: "boolean",
    aliases: ["lost time", "memory gap", "blackout"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "ictal_witness_present",
    behavior_label: "Witness present during event",
    prompt_example: "my partner saw it happen",
    data_type: "boolean",
    aliases: ["witness", "saw it", "witnessed"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "er_visit_for_seizure",
    behavior_label: "ER visit for seizure",
    prompt_example: "went to the er after",
    data_type: "boolean",
    aliases: ["er visit", "emergency room", "hospital"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "missed_neuro_appt",
    behavior_label: "Missed neurology appointment",
    prompt_example: "missed my neuro appt",
    data_type: "boolean",
    aliases: ["missed neurology", "missed appt"],
  },
  {
    category: "epilepsy_specific",
    behavior_key: "eeg_performed",
    behavior_label: "EEG performed",
    prompt_example: "had an eeg today",
    data_type: "boolean",
    aliases: ["eeg", "electroencephalogram"],
  },
];

async function main() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
    process.exit(1);
  }

  const supabase = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const payload = rows.map((r, i) => ({
    category: r.category,
    behavior_key: r.behavior_key,
    behavior_label: r.behavior_label,
    prompt_example: r.prompt_example,
    data_type: r.data_type,
    unit: r.unit ?? null,
    aliases: r.aliases ?? [],
    sort_order: i,
  }));

  console.log(`Upserting ${payload.length} behavior_taxonomy rows...`);
  const { error } = await supabase
    .from("behavior_taxonomy")
    .upsert(payload, { onConflict: "behavior_key" });

  if (error) {
    console.error("Upsert failed:", error);
    process.exit(1);
  }

  const { data: counts, error: cErr } = await supabase.from("behavior_taxonomy").select("category");
  if (cErr) {
    console.error(cErr);
    process.exit(1);
  }
  const byCat = (counts ?? []).reduce<Record<string, number>>((acc, r) => {
    acc[r.category] = (acc[r.category] ?? 0) + 1;
    return acc;
  }, {});
  console.log("Counts by category:");
  for (const [c, n] of Object.entries(byCat).sort()) {
    console.log(`  ${c}: ${n}`);
  }
  console.log(`Total: ${(counts ?? []).length}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
