import * as React from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { Loader2, FileText, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { resolveMedicalReportShareLink } from "@/lib/medical-report-share.functions";
import { noindexHead } from "@/lib/seo";

export const Route = createFileRoute("/share/report/$token")({
  head: () => noindexHead("Shared medical history · Purple"),
  component: SharedReportPage,
  errorComponent: ({ error }) => (
    <div className="mx-auto max-w-2xl px-5 py-16">
      <p className="text-sm text-destructive">{error.message}</p>
    </div>
  ),
});

function SharedReportPage() {
  const { token } = Route.useParams();
  const resolve = useServerFn(resolveMedicalReportShareLink);
  const { data, isLoading, error } = useQuery({
    queryKey: ["shared-report", token],
    queryFn: () => resolve({ data: { token } }),
    retry: false,
  });

  if (isLoading) {
    return (
      <div className="mx-auto max-w-2xl px-5 py-16">
        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
      </div>
    );
  }
  if (error || !data) {
    return (
      <div className="mx-auto max-w-2xl px-5 py-16">
        <h1 className="font-serif text-3xl text-foreground">Link unavailable</h1>
        <p className="mt-3 text-sm text-muted-foreground">
          {error instanceof Error ? error.message : "This share link can't be opened."}
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-5 sm:px-10 lg:px-16 pt-10 sm:pt-16 pb-24">
      <div className="flex items-center gap-2 text-xs uppercase tracking-wider text-muted-foreground">
        <FileText className="h-3.5 w-3.5" /> Shared medical history
      </div>
      <h1 className="mt-3 font-serif text-3xl sm:text-4xl text-foreground">
        {data.patientFirstName ? `${data.patientFirstName}'s health summary` : "Health summary"}
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        {data.windowFrom} → {data.windowTo} · Generated {new Date(data.generatedAt).toLocaleString()}
      </p>
      {data.viewerLabel && (
        <p className="mt-1 text-xs text-muted-foreground">Shared with: {data.viewerLabel}</p>
      )}
      <p className="mt-1 text-[11px] text-muted-foreground">
        Link expires {new Date(data.expiresAt).toLocaleString()}.
      </p>

      <div className="mt-6 flex gap-2">
        <Button asChild className="rounded-full">
          <a href={data.signedUrl} target="_blank" rel="noreferrer">
            <Download className="h-4 w-4 mr-1.5" /> Download PDF
          </a>
        </Button>
      </div>

      <div className="mt-6 rounded-2xl border border-border bg-card overflow-hidden">
        <iframe
          src={data.signedUrl}
          title="Medical history PDF"
          className="w-full h-[80vh] bg-background"
        />
      </div>

      <p className="mt-6 text-xs text-muted-foreground">
        This report was generated by the patient using Purple. It is not a clinical record and is
        provided for informational purposes only. Always cross-reference with primary sources.
      </p>
    </div>
  );
}