import { useMemo, useState, type ReactNode } from "react";
import { ArchiveRestore, BadgePercent, Check, ChevronRight, CircleAlert, FileDown, FileSearch, FileText, LockKeyhole, Mail, MessageCircle, Search, ShieldCheck, SlidersHorizontal, UserRound, UsersRound } from "lucide-react";
import { PilotAppShell } from "@/components/sections/pilot-app-shell";
import { DetailHeader } from "@/components/pages/pilot/detail/page";
import { PrivacyShield } from "@/components/pages/pilot/components/mobile-graphics";

type AdminArea = "Overview" | "Users" | "Rules" | "Resources" | "Promo codes" | "Migration export" | "Messages" | "Feedback" | "Contact" | "Community" | "Billing" | "Duplicate reports";

type AdminConfig = { heading: string; summary: string; icon: ReactNode; actions: Array<[string, string]>; primary?: string };

const configs: Record<AdminArea, AdminConfig> = {
  Overview: { heading: "Review operations without opening private journals.", summary: "Administrative access stays limited to system records and actions allowed by the signed-in role.", icon: <ShieldCheck size={23} />, actions: [["User access", "/admin/users"], ["System rules", "/admin/rules"], ["Billing operations", "/admin/billing"]] },
  Users: { heading: "Manage account access and roles.", summary: "Search account records, review status, and keep private health content outside the admin view.", icon: <UsersRound size={23} />, actions: [["Active accounts", "No live records loaded"], ["Pending access", "No live records loaded"], ["Role review", "Permissions are checked by Cloudflare services"]], primary: "Prepare account review" },
  Rules: { heading: "Review system rules before applying changes.", summary: "Rules affect classification and operational behavior, so changes need an explicit review step.", icon: <SlidersHorizontal size={23} />, actions: [["Active rules", "No production rules loaded"], ["Draft changes", "No draft changes"], ["Audit history", "Cloudflare events remain the source"]], primary: "Create rule draft" },
  Resources: { heading: "Curate public support resources.", summary: "Review titles, destinations, and publication status without exposing member data.", icon: <FileText size={23} />, actions: [["Published resources", "/resources"], ["Community resources", "/community/resources"], ["Draft review", "No drafts loaded"]], primary: "Prepare resource draft" },
  "Promo codes": { heading: "Manage promotional access deliberately.", summary: "Create limited codes, review their state, and avoid showing payment or member health information.", icon: <BadgePercent size={23} />, actions: [["Active codes", "No production codes loaded"], ["Expired codes", "No production codes loaded"], ["Usage review", "Counts come from Cloudflare billing records"]], primary: "Prepare promo code" },
  "Migration export": { heading: "Prepare a controlled migration export.", summary: "Choose the account scope and review the export manifest before any protected data moves.", icon: <FileDown size={23} />, actions: [["Export scope", "Account records only"], ["File manifest", "Not generated in this prototype"], ["Audit record", "Created by the Cloudflare workflow"]], primary: "Prepare export manifest" },
  Messages: { heading: "Review operational message queues.", summary: "Admin messages stay separate from private care conversations and journal content.", icon: <MessageCircle size={23} />, actions: [["Queued", "No live messages loaded"], ["Delivered", "No live messages loaded"], ["Suppressed", "No live messages loaded"]], primary: "Prepare queue review" },
  Feedback: { heading: "Triage product feedback with context.", summary: "Review topic, status, and response state without attaching private journal data.", icon: <CircleAlert size={23} />, actions: [["New feedback", "No live submissions loaded"], ["In review", "No live submissions loaded"], ["Resolved", "No live submissions loaded"]], primary: "Prepare feedback response" },
  Contact: { heading: "Review contact requests safely.", summary: "Contact metadata and message content remain separate from health records and account credentials.", icon: <Mail size={23} />, actions: [["New requests", "No live submissions loaded"], ["Assigned", "No live submissions loaded"], ["Closed", "No live submissions loaded"]], primary: "Prepare contact response" },
  Community: { heading: "Moderate public community activity.", summary: "Review public posts and reports without opening anyone’s private PurpleLife journal.", icon: <UsersRound size={23} />, actions: [["Posts awaiting review", "No live posts loaded"], ["Reported content", "No live reports loaded"], ["Community resources", "/community/resources"]], primary: "Open moderation review" },
  Billing: { heading: "Review subscription operations.", summary: "Billing status is handled separately from health records and never displays full payment credentials.", icon: <FileSearch size={23} />, actions: [["Subscription status", "No live records loaded"], ["Webhook events", "Cloudflare remains the operational source"], ["Promo codes", "/admin/promo"]], primary: "Prepare billing review" },
  "Duplicate reports": { heading: "Compare possible duplicate documents.", summary: "Review filenames, dates, and hashes before deciding whether two report records refer to the same source.", icon: <ArchiveRestore size={23} />, actions: [["Possible duplicates", "No live reports loaded"], ["Previously resolved", "No live reports loaded"], ["Source documents", "/reports/documents"]], primary: "Prepare duplicate review" },
};

/**
 * @ployComponent
 * @ployComponentId purplelife-admin-preview-page
 * @ployComponentType page
 * @ployComponentDescription Route-specific privacy-first Cloudflare administration pages for PurpleLife operations.
 * @ployComponentTags purplelife admin privacy operations
 * @ployComponentStatus experimental
 */
export function AdminPreviewPage({ area = "Overview" }: { area?: AdminArea }) {
  const config = configs[area];
  const [query, setQuery] = useState("");
  const [prepared, setPrepared] = useState(false);
  const rows = useMemo(() => config.actions.filter(([label, detail]) => `${label} ${detail}`.toLowerCase().includes(query.toLowerCase())), [config.actions, query]);
  return <PilotAppShell active="browse" landscape="insight"><DetailHeader title="Administration" backHref="/settings" /><section className="px-5 pt-1 text-center"><PrivacyShield className="mx-auto w-full max-w-[330px]" /><p className="-mt-2 text-[12px] font-semibold uppercase tracking-[0.06em] text-purplelife-accent">{area}</p><h1 className="mx-auto mt-2 max-w-[400px] text-[31px] font-semibold leading-[1.03] tracking-[-0.045em]">{config.heading}</h1><p className="mx-auto mt-3 max-w-[350px] text-[15px] leading-[1.45] text-purplelife-muted">{config.summary}</p></section><section className="mt-7 px-5"><label className="flex h-12 items-center gap-2 rounded-[18px] bg-white px-4 ring-1 ring-purplelife-line"><Search size={18} className="text-purplelife-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${area.toLowerCase()}`} className="min-w-0 flex-1 bg-transparent text-[14px] outline-none placeholder:text-purplelife-muted/60" /></label><div className="mt-4 overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-purplelife-line">{rows.map(([label, detail], index) => { const href = detail.startsWith("/") ? detail : undefined; const content = <><span className="grid size-11 shrink-0 place-items-center rounded-[15px] bg-purplelife-tint text-purplelife-accent">{index === 0 ? config.icon : <LockKeyhole size={19} />}</span><span className="min-w-0 flex-1 text-left"><span className="block text-[14px] font-semibold">{label}</span><span className="mt-1 block text-[12px] leading-[1.4] text-purplelife-muted">{href ? "Open the related workspace" : detail}</span></span>{href && <ChevronRight size={18} className="text-purplelife-muted" />}</>; return href ? <a key={label} href={href} className="flex items-center gap-3.5 border-b border-purplelife-line px-4 py-4 last:border-b-0">{content}</a> : <div key={label} className="flex items-center gap-3.5 border-b border-purplelife-line px-4 py-4 last:border-b-0">{content}</div>; })}</div>{config.primary && <button type="button" onClick={() => setPrepared(true)} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-[18px] bg-purplelife-accent text-[14px] font-semibold text-white">{prepared ? <Check size={18} /> : config.icon}{prepared ? "Review state prepared" : config.primary}</button>}<p className="mt-4 rounded-[22px] bg-purplelife-peach p-4 text-[12px] leading-[1.5] text-purplelife-muted">This prototype does not load, change, export, bill, or message production records.</p></section></PilotAppShell>;
}
