-- D1 core public schema (SQLite). Generated by scripts/cloudflare/generate-d1-schema.mjs
-- Replaces Supabase public.* tables. RLS is enforced in Worker code, not SQL.
-- Apply after 0001_auth.sql

CREATE TABLE IF NOT EXISTS condition_catalog (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS condition_catalog_user_idx ON condition_catalog (user_id);

CREATE TABLE IF NOT EXISTS behavior_taxonomy (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS behavior_taxonomy_user_idx ON behavior_taxonomy (user_id);

CREATE TABLE IF NOT EXISTS metric_dictionary (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS metric_dictionary_user_idx ON metric_dictionary (user_id);

CREATE TABLE IF NOT EXISTS platform_rules (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS platform_rules_user_idx ON platform_rules (user_id);

CREATE TABLE IF NOT EXISTS research_sources (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS research_sources_user_idx ON research_sources (user_id);

CREATE TABLE IF NOT EXISTS community_resources (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS community_resources_user_idx ON community_resources (user_id);

CREATE TABLE IF NOT EXISTS app_settings (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS app_settings_user_idx ON app_settings (user_id);

CREATE TABLE IF NOT EXISTS promo_codes (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS promo_codes_user_idx ON promo_codes (user_id);

CREATE TABLE IF NOT EXISTS admin_messages (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS admin_messages_user_idx ON admin_messages (user_id);

CREATE TABLE IF NOT EXISTS suppressed_emails (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS suppressed_emails_user_idx ON suppressed_emails (user_id);

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  date_of_birth TEXT,
  diagnosis TEXT,
  timezone TEXT,
  home_city TEXT,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  consent_research INTEGER NOT NULL DEFAULT 0,
  consent_share_with_caregivers INTEGER NOT NULL DEFAULT 0,
  caregiver_emails TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_memory (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS ai_memory_user_idx ON ai_memory (user_id);

CREATE TABLE IF NOT EXISTS alerts (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS alerts_user_idx ON alerts (user_id);

CREATE TABLE IF NOT EXISTS apple_health_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS apple_health_tokens_user_idx ON apple_health_tokens (user_id);

CREATE TABLE IF NOT EXISTS aura_events (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS aura_events_user_idx ON aura_events (user_id);

CREATE TABLE IF NOT EXISTS biometrics (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  source TEXT NOT NULL,
  hr_bpm REAL,
  hrv_rmssd_ms REAL,
  hrv_sdnn_ms REAL,
  resting_hr_bpm REAL,
  spo2_pct REAL,
  respiratory_rate_bpm REAL,
  body_temp_deviation_c REAL,
  skin_temp_c REAL,
  sleep_total_min REAL,
  sleep_rem_min REAL,
  sleep_deep_min REAL,
  sleep_light_min REAL,
  sleep_awake_min REAL,
  sleep_latency_min REAL,
  sleep_efficiency_pct REAL,
  sleep_score REAL,
  oura_readiness_score REAL,
  oura_stress_score REAL,
  oura_resilience_level TEXT,
  oura_activity_score REAL,
  whoop_recovery_pct REAL,
  whoop_strain REAL,
  whoop_sleep_performance_pct REAL,
  menstrual_phase TEXT,
  cycle_day INTEGER,
  steps INTEGER,
  active_calories REAL,
  workout_minutes REAL,
  raw_payload TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS biometrics_user_idx ON biometrics (user_id);

CREATE TABLE IF NOT EXISTS contact_messages (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS contact_messages_user_idx ON contact_messages (user_id);

CREATE TABLE IF NOT EXISTS feedback (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS feedback_user_idx ON feedback (user_id);

CREATE TABLE IF NOT EXISTS food_entries (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS food_entries_user_idx ON food_entries (user_id);

CREATE TABLE IF NOT EXISTS friendships (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS friendships_user_idx ON friendships (user_id);

CREATE TABLE IF NOT EXISTS hydration_intake (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS hydration_intake_user_idx ON hydration_intake (user_id);

CREATE TABLE IF NOT EXISTS metric_insights (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS metric_insights_user_idx ON metric_insights (user_id);

CREATE TABLE IF NOT EXISTS oura_tokens (
  user_id TEXT PRIMARY KEY,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  token_type TEXT,
  expires_at TEXT,
  scope TEXT,
  sync_mode TEXT DEFAULT 'visit',
  sync_interval_hours INTEGER DEFAULT 0,
  last_sync_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS oura_tokens_user_idx ON oura_tokens (user_id);

CREATE TABLE IF NOT EXISTS phi_access_log (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS phi_access_log_user_idx ON phi_access_log (user_id);

CREATE TABLE IF NOT EXISTS platform_rule_audit (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS platform_rule_audit_user_idx ON platform_rule_audit (user_id);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON push_subscriptions (user_id);

CREATE TABLE IF NOT EXISTS risk_forecasts (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS risk_forecasts_user_idx ON risk_forecasts (user_id);

CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS subscriptions_user_idx ON subscriptions (user_id);

CREATE TABLE IF NOT EXISTS trips (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS trips_user_idx ON trips (user_id);

CREATE TABLE IF NOT EXISTS user_roles (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS user_roles_user_idx ON user_roles (user_id);

CREATE TABLE IF NOT EXISTS vital_goals (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS vital_goals_user_idx ON vital_goals (user_id);

CREATE TABLE IF NOT EXISTS vitals_log (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS vitals_log_user_idx ON vitals_log (user_id);

CREATE TABLE IF NOT EXISTS whoop_tokens (
  user_id TEXT PRIMARY KEY,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  token_type TEXT,
  expires_at TEXT,
  scope TEXT,
  sync_mode TEXT DEFAULT 'visit',
  sync_interval_hours INTEGER DEFAULT 0,
  last_sync_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS whoop_tokens_user_idx ON whoop_tokens (user_id);

CREATE TABLE IF NOT EXISTS email_send_log (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS email_send_log_user_idx ON email_send_log (user_id);

CREATE TABLE IF NOT EXISTS email_send_state (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS email_send_state_user_idx ON email_send_state (user_id);

CREATE TABLE IF NOT EXISTS email_unsubscribe_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS email_unsubscribe_tokens_user_idx ON email_unsubscribe_tokens (user_id);

CREATE TABLE IF NOT EXISTS medications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT,
  prescriber TEXT,
  times_of_day TEXT NOT NULL DEFAULT '[]',
  start_date TEXT,
  end_date TEXT,
  refill_date TEXT,
  pills_remaining INTEGER,
  notes TEXT,
  is_rescue INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medications_user_idx ON medications (user_id);

CREATE TABLE IF NOT EXISTS seizure_events (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS seizure_events_user_idx ON seizure_events (user_id);

CREATE TABLE IF NOT EXISTS medical_reports (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medical_reports_user_idx ON medical_reports (user_id);

CREATE TABLE IF NOT EXISTS dna_files (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS dna_files_user_idx ON dna_files (user_id);

CREATE TABLE IF NOT EXISTS care_relationships (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_relationships_user_idx ON care_relationships (user_id);

CREATE TABLE IF NOT EXISTS community_posts (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS community_posts_user_idx ON community_posts (user_id);

CREATE TABLE IF NOT EXISTS report_documents (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS report_documents_user_idx ON report_documents (user_id);

CREATE TABLE IF NOT EXISTS medication_doses (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medication_doses_user_idx ON medication_doses (user_id);

CREATE TABLE IF NOT EXISTS medication_side_effects (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medication_side_effects_user_idx ON medication_side_effects (user_id);

CREATE TABLE IF NOT EXISTS medical_report_schedules (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medical_report_schedules_user_idx ON medical_report_schedules (user_id);

CREATE TABLE IF NOT EXISTS journal_entries (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  captured_at TEXT NOT NULL DEFAULT (datetime('now')),
  kind TEXT NOT NULL DEFAULT 'text',
  status TEXT NOT NULL DEFAULT 'processing',
  text TEXT,
  voice_transcript TEXT,
  media_urls TEXT NOT NULL DEFAULT '[]',
  ai_summary TEXT,
  ai_tags TEXT NOT NULL DEFAULT '[]',
  ai_extracted TEXT,
  linked_seizure_id TEXT,
  linked_medication_dose_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS journal_entries_user_idx ON journal_entries (user_id);

CREATE TABLE IF NOT EXISTS dna_variants (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS dna_variants_user_idx ON dna_variants (user_id);

CREATE TABLE IF NOT EXISTS care_threads (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_threads_user_idx ON care_threads (user_id);

CREATE TABLE IF NOT EXISTS promo_code_redemptions (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS promo_code_redemptions_user_idx ON promo_code_redemptions (user_id);

CREATE TABLE IF NOT EXISTS daily_behaviors (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS daily_behaviors_user_idx ON daily_behaviors (user_id);

CREATE TABLE IF NOT EXISTS care_thread_participants (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_thread_participants_user_idx ON care_thread_participants (user_id);

CREATE TABLE IF NOT EXISTS care_messages (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_messages_user_idx ON care_messages (user_id);

CREATE TABLE IF NOT EXISTS care_scopes (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_scopes_user_idx ON care_scopes (user_id);

CREATE TABLE IF NOT EXISTS care_caregiver_visits (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_caregiver_visits_user_idx ON care_caregiver_visits (user_id);

CREATE TABLE IF NOT EXISTS care_audit_log (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS care_audit_log_user_idx ON care_audit_log (user_id);

CREATE TABLE IF NOT EXISTS pending_changes (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS pending_changes_user_idx ON pending_changes (user_id);

CREATE TABLE IF NOT EXISTS community_comments (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS community_comments_user_idx ON community_comments (user_id);

CREATE TABLE IF NOT EXISTS community_reactions (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS community_reactions_user_idx ON community_reactions (user_id);

CREATE TABLE IF NOT EXISTS community_reports (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS community_reports_user_idx ON community_reports (user_id);

CREATE TABLE IF NOT EXISTS medical_report_public_links (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medical_report_public_links_user_idx ON medical_report_public_links (user_id);

CREATE TABLE IF NOT EXISTS medical_report_shares (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS medical_report_shares_user_idx ON medical_report_shares (user_id);

CREATE TABLE IF NOT EXISTS report_identity_aliases (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS report_identity_aliases_user_idx ON report_identity_aliases (user_id);

CREATE TABLE IF NOT EXISTS report_metric_preferences (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS report_metric_preferences_user_idx ON report_metric_preferences (user_id);

CREATE TABLE IF NOT EXISTS report_metrics (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS report_metrics_user_idx ON report_metrics (user_id);

CREATE TABLE IF NOT EXISTS notification_delivery_log (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS notification_delivery_log_user_idx ON notification_delivery_log (user_id);

CREATE TABLE IF NOT EXISTS admin_message_reads (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS admin_message_reads_user_idx ON admin_message_reads (user_id);

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0002_core_schema');
