/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppVitalsRouteImport } from './routes/_app/vitals'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppMyHealthRouteImport } from './routes/_app/my-health'
import { Route as AppMedsRouteImport } from './routes/_app/meds'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppCharterRouteImport } from './routes/_app/charter'
import { Route as AppJournalIndexRouteImport } from './routes/_app/journal.index'
import { Route as OauthOuraCallbackRouteImport } from './routes/oauth.oura.callback'
import { Route as AppTodayRiskRouteImport } from './routes/_app/today.risk'
import { Route as AppSeizuresNewRouteImport } from './routes/_app/seizures.new'
import { Route as AppMedsMedIdRouteImport } from './routes/_app/meds.$medId'
import { Route as AppJournalNewRouteImport } from './routes/_app/journal.new'
import { Route as ApiPublicHooksRiskForecasterRouteImport } from './routes/api/public/hooks/risk-forecaster'
import { Route as AppJournalEntryIdEditRouteImport } from './routes/_app/journal.$entryId.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppVitalsRoute = AppVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppMyHealthRoute = AppMyHealthRouteImport.update({
  id: '/my-health',
  path: '/my-health',
  getParentRoute: () => AppRoute,
} as any)
const AppMedsRoute = AppMedsRouteImport.update({
  id: '/meds',
  path: '/meds',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCharterRoute = AppCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalIndexRoute = AppJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => AppRoute,
} as any)
const OauthOuraCallbackRoute = OauthOuraCallbackRouteImport.update({
  id: '/oauth/oura/callback',
  path: '/oauth/oura/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRiskRoute = AppTodayRiskRouteImport.update({
  id: '/today/risk',
  path: '/today/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSeizuresNewRoute = AppSeizuresNewRouteImport.update({
  id: '/seizures/new',
  path: '/seizures/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMedsMedIdRoute = AppMedsMedIdRouteImport.update({
  id: '/$medId',
  path: '/$medId',
  getParentRoute: () => AppMedsRoute,
} as any)
const AppJournalNewRoute = AppJournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksRiskForecasterRoute =
  ApiPublicHooksRiskForecasterRouteImport.update({
    id: '/api/public/hooks/risk-forecaster',
    path: '/api/public/hooks/risk-forecaster',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppJournalEntryIdEditRoute = AppJournalEntryIdEditRouteImport.update({
  id: '/journal/$entryId/edit',
  path: '/journal/$entryId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/charter': typeof AppCharterRoute
  '/chat': typeof AppChatRoute
  '/insights': typeof AppInsightsRoute
  '/meds': typeof AppMedsRouteWithChildren
  '/my-health': typeof AppMyHealthRoute
  '/privacy': typeof AppPrivacyRoute
  '/settings': typeof AppSettingsRoute
  '/terms': typeof AppTermsRoute
  '/vitals': typeof AppVitalsRoute
  '/welcome': typeof AppWelcomeRoute
  '/journal/new': typeof AppJournalNewRoute
  '/meds/$medId': typeof AppMedsMedIdRoute
  '/seizures/new': typeof AppSeizuresNewRoute
  '/today/risk': typeof AppTodayRiskRoute
  '/oauth/oura/callback': typeof OauthOuraCallbackRoute
  '/journal/': typeof AppJournalIndexRoute
  '/journal/$entryId/edit': typeof AppJournalEntryIdEditRoute
  '/api/public/hooks/risk-forecaster': typeof ApiPublicHooksRiskForecasterRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/charter': typeof AppCharterRoute
  '/chat': typeof AppChatRoute
  '/insights': typeof AppInsightsRoute
  '/meds': typeof AppMedsRouteWithChildren
  '/my-health': typeof AppMyHealthRoute
  '/privacy': typeof AppPrivacyRoute
  '/settings': typeof AppSettingsRoute
  '/terms': typeof AppTermsRoute
  '/vitals': typeof AppVitalsRoute
  '/welcome': typeof AppWelcomeRoute
  '/': typeof AppIndexRoute
  '/journal/new': typeof AppJournalNewRoute
  '/meds/$medId': typeof AppMedsMedIdRoute
  '/seizures/new': typeof AppSeizuresNewRoute
  '/today/risk': typeof AppTodayRiskRoute
  '/oauth/oura/callback': typeof OauthOuraCallbackRoute
  '/journal': typeof AppJournalIndexRoute
  '/journal/$entryId/edit': typeof AppJournalEntryIdEditRoute
  '/api/public/hooks/risk-forecaster': typeof ApiPublicHooksRiskForecasterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/_app/charter': typeof AppCharterRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/meds': typeof AppMedsRouteWithChildren
  '/_app/my-health': typeof AppMyHealthRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/vitals': typeof AppVitalsRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/journal/new': typeof AppJournalNewRoute
  '/_app/meds/$medId': typeof AppMedsMedIdRoute
  '/_app/seizures/new': typeof AppSeizuresNewRoute
  '/_app/today/risk': typeof AppTodayRiskRoute
  '/oauth/oura/callback': typeof OauthOuraCallbackRoute
  '/_app/journal/': typeof AppJournalIndexRoute
  '/_app/journal/$entryId/edit': typeof AppJournalEntryIdEditRoute
  '/api/public/hooks/risk-forecaster': typeof ApiPublicHooksRiskForecasterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/charter'
    | '/chat'
    | '/insights'
    | '/meds'
    | '/my-health'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/vitals'
    | '/welcome'
    | '/journal/new'
    | '/meds/$medId'
    | '/seizures/new'
    | '/today/risk'
    | '/oauth/oura/callback'
    | '/journal/'
    | '/journal/$entryId/edit'
    | '/api/public/hooks/risk-forecaster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/sign-in'
    | '/charter'
    | '/chat'
    | '/insights'
    | '/meds'
    | '/my-health'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/vitals'
    | '/welcome'
    | '/'
    | '/journal/new'
    | '/meds/$medId'
    | '/seizures/new'
    | '/today/risk'
    | '/oauth/oura/callback'
    | '/journal'
    | '/journal/$entryId/edit'
    | '/api/public/hooks/risk-forecaster'
  id:
    | '__root__'
    | '/_app'
    | '/reset-password'
    | '/sign-in'
    | '/_app/charter'
    | '/_app/chat'
    | '/_app/insights'
    | '/_app/meds'
    | '/_app/my-health'
    | '/_app/privacy'
    | '/_app/settings'
    | '/_app/terms'
    | '/_app/vitals'
    | '/_app/welcome'
    | '/_app/'
    | '/_app/journal/new'
    | '/_app/meds/$medId'
    | '/_app/seizures/new'
    | '/_app/today/risk'
    | '/oauth/oura/callback'
    | '/_app/journal/'
    | '/_app/journal/$entryId/edit'
    | '/api/public/hooks/risk-forecaster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  OauthOuraCallbackRoute: typeof OauthOuraCallbackRoute
  ApiPublicHooksRiskForecasterRoute: typeof ApiPublicHooksRiskForecasterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vitals': {
      id: '/_app/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AppVitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-health': {
      id: '/_app/my-health'
      path: '/my-health'
      fullPath: '/my-health'
      preLoaderRoute: typeof AppMyHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meds': {
      id: '/_app/meds'
      path: '/meds'
      fullPath: '/meds'
      preLoaderRoute: typeof AppMedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charter': {
      id: '/_app/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof AppCharterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal/': {
      id: '/_app/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AppJournalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/oura/callback': {
      id: '/oauth/oura/callback'
      path: '/oauth/oura/callback'
      fullPath: '/oauth/oura/callback'
      preLoaderRoute: typeof OauthOuraCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today/risk': {
      id: '/_app/today/risk'
      path: '/today/risk'
      fullPath: '/today/risk'
      preLoaderRoute: typeof AppTodayRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seizures/new': {
      id: '/_app/seizures/new'
      path: '/seizures/new'
      fullPath: '/seizures/new'
      preLoaderRoute: typeof AppSeizuresNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meds/$medId': {
      id: '/_app/meds/$medId'
      path: '/$medId'
      fullPath: '/meds/$medId'
      preLoaderRoute: typeof AppMedsMedIdRouteImport
      parentRoute: typeof AppMedsRoute
    }
    '/_app/journal/new': {
      id: '/_app/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AppJournalNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/risk-forecaster': {
      id: '/api/public/hooks/risk-forecaster'
      path: '/api/public/hooks/risk-forecaster'
      fullPath: '/api/public/hooks/risk-forecaster'
      preLoaderRoute: typeof ApiPublicHooksRiskForecasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/journal/$entryId/edit': {
      id: '/_app/journal/$entryId/edit'
      path: '/journal/$entryId/edit'
      fullPath: '/journal/$entryId/edit'
      preLoaderRoute: typeof AppJournalEntryIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMedsRouteChildren {
  AppMedsMedIdRoute: typeof AppMedsMedIdRoute
}

const AppMedsRouteChildren: AppMedsRouteChildren = {
  AppMedsMedIdRoute: AppMedsMedIdRoute,
}

const AppMedsRouteWithChildren =
  AppMedsRoute._addFileChildren(AppMedsRouteChildren)

interface AppRouteChildren {
  AppCharterRoute: typeof AppCharterRoute
  AppChatRoute: typeof AppChatRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMedsRoute: typeof AppMedsRouteWithChildren
  AppMyHealthRoute: typeof AppMyHealthRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTermsRoute: typeof AppTermsRoute
  AppVitalsRoute: typeof AppVitalsRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJournalNewRoute: typeof AppJournalNewRoute
  AppSeizuresNewRoute: typeof AppSeizuresNewRoute
  AppTodayRiskRoute: typeof AppTodayRiskRoute
  AppJournalIndexRoute: typeof AppJournalIndexRoute
  AppJournalEntryIdEditRoute: typeof AppJournalEntryIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCharterRoute: AppCharterRoute,
  AppChatRoute: AppChatRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMedsRoute: AppMedsRouteWithChildren,
  AppMyHealthRoute: AppMyHealthRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTermsRoute: AppTermsRoute,
  AppVitalsRoute: AppVitalsRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppJournalNewRoute: AppJournalNewRoute,
  AppSeizuresNewRoute: AppSeizuresNewRoute,
  AppTodayRiskRoute: AppTodayRiskRoute,
  AppJournalIndexRoute: AppJournalIndexRoute,
  AppJournalEntryIdEditRoute: AppJournalEntryIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  OauthOuraCallbackRoute: OauthOuraCallbackRoute,
  ApiPublicHooksRiskForecasterRoute: ApiPublicHooksRiskForecasterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
